---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-training
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Kube Training Project
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  sourceNamespaces:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
