apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: local-kube-cluster

  annotations:
    managed-by: argocd.argoproj.io

  labels:
    argocd.argoproj.io/secret-type: cluster
    name: "local-kube-cluster"
    environment: "demo"
    edge-system: "local"
    l2-lb-enabled: "false"
    serial: "01"
    site: "lcl"
    storage-backend: "none"

stringData:
  config: '{"tlsClientConfig":{"insecure":false}}'
  name: 'local-kube-cluster'
  server: 'https://kubernetes.default.svc'