{{- $token := .Files.Get "files/.token" -}}
{{ if not $token }}
  {{ fail ".token file not found or empty, get the GitHub PAT from the Automation Keyvault and save it into files/.token" }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gh-dhl-infra-features-topic-sync
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: "git"
  url: "https://github.com/dhlparcel/kube-training.git
  username: "not-used"
  password: "{{ $token }}"
